# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1051, 856)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1031, 831))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.kategori = QtWidgets.QVBoxLayout()
        self.kategori.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.kategori.setContentsMargins(-1, -1, 0, -1)
        self.kategori.setObjectName("kategori")
        self.treeWidget = QtWidgets.QTreeWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMaximumSize(QtCore.QSize(170, 16777215))
        self.treeWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.treeWidget.setMouseTracking(False)
        self.treeWidget.setTabletTracking(False)
        self.treeWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.treeWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.treeWidget.setAcceptDrops(True)
        self.treeWidget.setStyleSheet("QTreeWidget {\n"
"    background-color: #f0f0f0; /* Arka plan rengi */\n"
"    border: 1px solid #888; /* Kenar rengi */\n"
"}\n"
"\n"
"QTreeWidget::item {\n"
"    padding: 10px; /* Öğeler arasındaki boşluk */\n"
"}\n"
"\n"
"QTreeWidget::item:selected {\n"
"    background-color: #007BFF; /* Seçilen öğe arka plan rengi */\n"
"    color: white; /* Seçilen öğe metin rengi */\n"
"    border: none; /* Seçili öğenin etrafındaki çerçeveyi kaldır */\n"
"    outline: none;\n"
"}\n"
"\n"
"QTreeWidget::item:hover {\n"
"    background-color: #007BFF; /* Üzerine gelindiğinde arka plan rengi */\n"
"    color: white; /* Üzerine gelindiğinde metin rengi */\n"
"}\n"
"\n"
"QTreeWidget::branch {\n"
"    background: transparent; /* Dal arka plan rengi */\n"
"}\n"
"\n"
"QTreeWidget::item:focus {\n"
"    border:none;\n"
"    outline: none; /* Noktalı kutuyu kaldır */\n"
"}")
        self.treeWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.treeWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.treeWidget.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.treeWidget.setTabKeyNavigation(True)
        self.treeWidget.setDragEnabled(True)
        self.treeWidget.setDragDropOverwriteMode(False)
        self.treeWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.treeWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.treeWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.treeWidget.setIndentation(20)
        self.treeWidget.setUniformRowHeights(False)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setAllColumnsShowFocus(True)
        self.treeWidget.setWordWrap(True)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.kategori.addWidget(self.treeWidget)
        self.horizontalLayout_2.addLayout(self.kategori)
        self.haber = QtWidgets.QVBoxLayout()
        self.haber.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.haber.setContentsMargins(-1, -1, 0, -1)
        self.haber.setObjectName("haber")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(250)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: #4682B4; /* Daha koyu mavi */\n"
"    color: white\n"
";\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.haber.addWidget(self.label)
        self.textBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(250)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(50, 50))
        self.textBrowser.setMaximumSize(QtCore.QSize(1000, 1000))
        self.textBrowser.setSizeIncrement(QtCore.QSize(250, 250))
        self.textBrowser.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textBrowser.setStyleSheet("            QTextBrowser {\n"
"                background-color: #f0f0f0;  /* Arka plan rengi */\n"
"                color: #333;                 /* Metin rengi */\n"
"                font-size: 14px;             /* Yazı boyutu */\n"
"                padding: 10px;               /* İç boşluk */\n"
"                border: 1px solid #aaa;      /* Kenar rengi */\n"
"                border-radius: 5px;          /* Kenar yuvarlama */\n"
"            }")
        self.textBrowser.setLineWidth(0)
        self.textBrowser.setMidLineWidth(0)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.haber.addWidget(self.textBrowser)
        self.horizontalLayout_2.addLayout(self.haber)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "KATEGORİLER"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "SON DAKİKA"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "CNN"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "NTV"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "HÜRRİYET"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "MİLLİYET"))
        self.treeWidget.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "A HABER"))
        self.treeWidget.topLevelItem(0).child(5).setText(0, _translate("MainWindow", "CUMHURİYET"))
        self.treeWidget.topLevelItem(0).child(6).setText(0, _translate("MainWindow", "YENİ AKİT"))
        self.treeWidget.topLevelItem(0).child(7).setText(0, _translate("MainWindow", "ANA YURT"))
        self.treeWidget.topLevelItem(0).child(8).setText(0, _translate("MainWindow", "SABAH"))
        self.treeWidget.topLevelItem(0).child(9).setText(0, _translate("MainWindow", "TAKVİM"))
        self.treeWidget.topLevelItem(0).child(10).setText(0, _translate("MainWindow", "YENİ ŞAFAK"))
        self.treeWidget.topLevelItem(0).child(11).setText(0, _translate("MainWindow", "HABERTÜRK"))
        self.treeWidget.topLevelItem(0).child(12).setText(0, _translate("MainWindow", "TRT HABER"))
        self.treeWidget.topLevelItem(0).child(13).setText(0, _translate("MainWindow", "BBC TÜRKÇE"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "EKONOMİ"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "A PARA"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "CNN EKONOMİ"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "HÜRRİYET EKONOMİ"))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "MİLLİYET EKONOMİ"))
        self.treeWidget.topLevelItem(1).child(4).setText(0, _translate("MainWindow", "SABAH EKONOMİ"))
        self.treeWidget.topLevelItem(1).child(5).setText(0, _translate("MainWindow", "TAKVİM EKONOMİ"))
        self.treeWidget.topLevelItem(1).child(6).setText(0, _translate("MainWindow", "YENİ AKİT EKONOMİ"))
        self.treeWidget.topLevelItem(1).child(7).setText(0, _translate("MainWindow", "YENİ ŞAFAK EKONOMİ"))
        self.treeWidget.topLevelItem(1).child(8).setText(0, _translate("MainWindow", "NTV EKONOMİ"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "SİYASET"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "YENİ AKİT SİYASET"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "MİLLİYET SİYASET"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "MAGAZİN"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "HÜRRİYET MAGAZİN"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "MİLLİYET MAGAZİN"))
        self.treeWidget.topLevelItem(3).child(2).setText(0, _translate("MainWindow", "YENİ AKİT MAGAZİN"))
        self.treeWidget.topLevelItem(3).child(3).setText(0, _translate("MainWindow", "A MAGAZİN"))
        self.treeWidget.topLevelItem(3).child(4).setText(0, _translate("MainWindow", "CNN MAGAZİN"))
        self.treeWidget.topLevelItem(3).child(5).setText(0, _translate("MainWindow", "MYNET MAGAZİN"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "GLOBAL"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "DÜNYA"))
        self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "HÜRRİYET DÜNYA"))
        self.treeWidget.topLevelItem(4).child(2).setText(0, _translate("MainWindow", "MİLLİYET DÜNYA"))
        self.treeWidget.topLevelItem(4).child(3).setText(0, _translate("MainWindow", "SABAH DÜNYA"))
        self.treeWidget.topLevelItem(4).child(4).setText(0, _translate("MainWindow", "YENİ AKİT DÜNYA"))
        self.treeWidget.topLevelItem(4).child(5).setText(0, _translate("MainWindow", "YENİ ŞAFAK DÜNYA"))
        self.treeWidget.topLevelItem(4).child(6).setText(0, _translate("MainWindow", "A DÜNYA"))
        self.treeWidget.topLevelItem(4).child(7).setText(0, _translate("MainWindow", "CNN DÜNYA"))
        self.treeWidget.topLevelItem(4).child(8).setText(0, _translate("MainWindow", "MYNET DÜNYA"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "HABER RADAR"))
